let stockProductos = [
    {id: 1, nombre: "Barra Invitacion 1", tipo: "Chocolate", cantidad: 1, desc: "Barra de Chocolate semi-amargo con datos de la fiesta en la envoltura", precio: 1000, img: './img/BarraInvitacion.jpeg'},
    {id: 2, nombre: "Bombas de chocolate 1", tipo: "Esfera", cantidad: 1, desc: "Bombas de Chocolate relleno de bombon o lunetas", precio: 1000, img: './img/BombasDeChocolate.jpg'},
    {id: 3, nombre: "Calavera de Chocolate 1", tipo: "Calavera", cantidad: 1, desc: "Calavera de Chocolate semi-amargo", precio: 1000, img: './img/CalaverasDeChocolate.jpeg'},
    {id: 4, nombre: "Corazon de Arroz inflado 1", tipo: "Paleta", cantidad: 1, desc: "Paleta de Cereal cubierta de Chocolate", precio: 1000, img: './img/CorazonDeCereal.jpeg'},
    {id: 5, nombre: "Magnum de Chocolate 1", tipo: "Paleta", cantidad: 1, desc: "Paleta Magnum de Chocolate-blanco", precio: 1000, img: './img/MagnumDeChocolate.jpeg'},
    {id: 6, nombre: "Mini Emogis 1", tipo: "paleta", cantidad: 1, desc: "Paleta de chocolate y ceral", precio: 1000, img: './img/MiniEmogisPaletas.jpeg'},
    {id: 7, nombre: "Mini Magnum 1", tipo: "paleta", cantidad: 1, desc: "Paleta de chocolate con amarnato y arroz inflado cubiertas de chocolate", precio: 1000, img: './img/MiniMagnumAmaranto.jpeg'},
    {id: 8, nombre: "Paletas Personalizada 1", tipo: "Corazon", cantidad: 1, desc: "Paleta en forma de corazon con frase personalizada, chocolate semi-amargo", precio: 1000, img: "./img/PaletasPersonalizadasCereal.jpeg"},
    {id: 9, nombre: "Brocheta de bombon 1", tipo: "Brocheta", cantidad: 1, desc: "Bombon cubierto de chocolate, decorado con granillo de chocolate o nuez", precio: 1000, img: "./img/bombon.jpg"},
    {id: 10, nombre: "Paletas Toda Ocacion 1", tipo: "Paleta", cantidad: 1, desc: "paleta chocolate macizo", precio: 1000, img: './img/chocolate-paletas.jpg'},
    {id: 11, nombre: "Manzanas cubiertas 1", tipo: "Manzana", cantidad: 1, desc: "Manzana cubierta de chocolate", precio: 1000, img: './img/manzanas-chocolate.jpg'},
    {id: 12, nombre: "Magnum Pinguino 1", tipo: "Paleta", cantidad: 1, desc: "Paleta rellena de pan de chocolate", precio: 1000, img: './img/choco-pinguino.jpg'},
    {id: 13, nombre: "Enjambre de chocolate 1", tipo: "enjambre", cantidad: 1, desc: "Enjambre de cereal cubierto de chocolate", precio: 1000, img: './img/enjambre-de-chocolate.jpg'},
] //esto es un objeto json
